### ISSUE TITLE
Add an "Open Recent Files" menu option

### ISSUE THREAD

**Issue by xgouchet** [DaveJarvis/scrivenvar#89]
This is a feature that many editors have, and one that I find myself using very regularly.

If that's something you're interested in having, I can push a PR, possibly storing a `recentFiles`  property in the Preferences.

**Comment by DaveJarvis** [comment]
Thank you, Xavier. This feature, while useful in the short-term, is solving a problem that is likely addressed by other open issues. Here's the current long-term plan regarding files:

1. Add dockable panels to the UI (#65).
1. Add dockable file system explorer panels (#68).
1. Add a workspace concept (#77).

Collectively, this would make recent files moot because you can set up dockable file explorers (per workspace). A list of recent workspaces would be helpful.

Feel free to re-open if you have more thoughts on this subject.

**Comment by DaveJarvis** [comment]
@xgouchet, it took a while, but there's now a file manager available through the UI. The file manager remembers the most recently used directory. If you're still using the app, let me know if the file manager doesn't quite provide the functionality you'd like.
